"""Generate mt5/experts/early_closes.mqh: sessions that end before 23:30 in the rebuilt NQ data.

Each listed date gets a flatten time = open of its last M30 bar (e.g. last minute 19:59 ->
flatten at 19:30), the same rule as a normal day (last bar 23:30). Every date was checked
against the published schedule (holiday rules, the 2010-2012 Friday 15:15 CT close, announced
state-funeral closures; Hurricane Sandy 2012 is the only unscheduled one). See docs/DATA_BUILD.md.

Usage: python build_early_close_calendar.py <MT5 bar CSV> [--exclude-after YYYY.MM.DD]
"""

import argparse

import pandas as pd

from project_paths import PROJECT_ROOT

OUT = PROJECT_ROOT / "mt5" / "experts" / "early_closes.mqh"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("csv")
    ap.add_argument("--exclude-after", default="2026.09.30", help="last complete session date in the data")
    args = ap.parse_args()

    bars = pd.read_csv(args.csv, sep="\t", usecols=["<DATE>", "<TIME>"])
    last = bars.groupby("<DATE>")["<TIME>"].max()
    early = last[(last < "23:30:00") & (last.index <= args.exclude_after)]
    dates, minutes = [], []
    for d, t in early.items():
        h, m = int(t[:2]), int(t[3:5])
        dates.append(d.replace(".", ""))
        minutes.append(h * 60 + (m // 30) * 30)      # open of the last M30 bar

    lines = [
        "// Generated by python/build_early_close_calendar.py - do not edit by hand.",
        f"// {len(dates)} sessions that end before 23:30 (data clock: Chicago + 8 h).",
        "// EC_DATE = yyyymmdd (sorted), EC_FLAT_MIN = flatten time in minutes after midnight.",
        f"#define EC_COUNT {len(dates)}",
        "const int EC_DATE[EC_COUNT] = {" + ",".join(dates) + "};",
        "const int EC_FLAT_MIN[EC_COUNT] = {" + ",".join(map(str, minutes)) + "};",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")   # Windows text mode writes CRLF
    print(f"Wrote {len(dates)} early-close sessions to {OUT}")


if __name__ == "__main__":
    main()
