"""Build mt5/experts/RR_r_MFE_buy-stop-entry_breakout.cs: the exact Q18 stage-2 tested EA as one file.

Inlines every include of Reports/levels/breakout_standalone_20261004/RTL_level_gate.mq5 and sets each input's
default to the value used in the tested trading run (breakout_standalone_20261004_trade.ini), so a manual
tester run with default inputs reproduces Q18 stage 2. Tester-only (the research OnInit refuses live charts).
"""
import re

from analyze_price_levels import ROOT, sha256

RUN = ROOT / "Reports" / "levels" / "breakout_standalone_20261004"
SOURCE = RUN / "RTL_level_gate.mq5"
INI = RUN / "breakout_standalone_20261004_trade.ini"
OUT = ROOT / "mt5" / "experts" / "RR_r_MFE_buy-stop-entry_breakout.cs"
RUN_TAG = "breakout_manual"


def tested_inputs():
    section = INI.read_text(encoding="utf-16").split("[TesterInputs]")[1].split("[")[0]
    values = {}
    for line in section.splitlines():
        if "=" in line:
            key, value = line.split("=", 1)
            values[key.strip()] = value.split("||")[0].strip()
    values["RunTag"] = RUN_TAG
    return values


def main():
    text = SOURCE.read_text(encoding="utf-8-sig")
    for name in re.findall(r'#include "([^"]+)"', text):
        body = (RUN / name).read_text(encoding="utf-8-sig")
        text = re.sub(rf'#include "{re.escape(name)}"[^\n]*',
                      lambda m: f"// ---- begin inlined {name} ----\n{body.rstrip()}\n// ---- end inlined {name} ----", text, count=1)
    assert "#include" not in text
    for key, value in tested_inputs().items():
        pattern = rf"(input\s+(\w+)\s+{key}\s*=\s*)([^;]+);"
        match = re.search(pattern, text)
        assert match and len(re.findall(pattern, text)) == 1, key
        kind = match.group(2)
        literal = f'"{value}"' if kind == "string" else value
        text = text[:match.start(3)] + literal + text[match.end(3):]
    header = ("//+------------------------------------------------------------------+\n"
              "//| RR_r_MFE_buy-stop-entry_breakout - Q18 horizontal breakout EA      |\n"
              "//| Generated by python/build_breakout_ea.py - do not edit by hand.    |\n"
              "//| The exact EA of Q18 stage 2 (docs/levels/BREAKOUT_RESULTS.md) with  |\n"
              "//| all includes inlined; input defaults = the tested run's inputs.    |\n"
              "//| GateMode 2 = trade only breakout tests; 0 = plain RTL baseline;    |\n"
              "//| 1 = classify/log only. Strategy tester only.                       |\n"
              f"//| Source sha256 {sha256(SOURCE)[:16]}...                             |\n"
              "//+------------------------------------------------------------------+\n")
    OUT.write_text(header + text, encoding="utf-8")
    print(OUT)


if __name__ == "__main__":
    main()
