"""Build a standalone Q20 tester EA without changing the completed research runs.

Defaults come from the saved primary INI. RiskReward controls the bar-close
target in every regime. At 1R the target is identical to the studied setting.
Run from the project root: venv/Scripts/python.exe python/build_trendline_limit_ea.py
"""
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RUN = ROOT / "Reports" / "trendlines" / "trendline_limit_runs_20261005"
OUT = ROOT / "mt5" / "experts" / "RTL_trendline_limit_manual.mq5"


def use_risk_reward(text):
    old = "   tr_rr=(tr_regime==1 ? BullRR : (tr_regime==-1 ? BearRR : 1.0));"
    assert text.count(old) == 1, "Unexpected inherited RR assignment"
    text = text.replace(old, "   tr_rr=RiskReward;   // Q20: target in every regime")
    old = "int OnInit()\n{"
    assert text.count(old) == 1
    text = text.replace(old, old + "\n   if(!MathIsValidNumber(RiskReward) || RiskReward<=0) return INIT_PARAMETERS_INCORRECT;")
    # Keep constants for the inherited stats schema, without misleading inputs.
    for name in ("BullRR", "BearRR"):
        text, count = re.subn(rf"input double {name}=1\.0;", f"const double {name}=1.0; // unused by Q20", text)
        assert count == 1, name
    return text


def build():
    source = RUN / "RTL_trendline_limit.mq5"
    text = source.read_text(encoding="utf-8-sig")
    for name in re.findall(r'#include "([^\"]+)"', text):
        body = (RUN / name).read_text(encoding="utf-8-sig")
        text = re.sub(rf'#include "{re.escape(name)}"[^\n]*',
                      lambda m: f"// begin {name}\n{body.rstrip()}\n// end {name}", text, count=1)
    assert "#include" not in text
    text = use_risk_reward(text)
    ini = (RUN / "trendline_limit_runs_20261005_primary.ini").read_text(encoding="utf-16")
    section = ini.split("[TesterInputs]", 1)[1].split("[", 1)[0]
    for line in section.splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key, value = key.strip(), value.split("||", 1)[0].strip()
        if key in ("BullRR", "BearRR"):
            assert float(value) == 1.0
            continue
        if key == "RunTag":
            value = "trendline_limit_manual"
        pattern = rf"(input\s+(\w+)\s+{re.escape(key)}\s*=\s*)([^;]+);"
        matches = list(re.finditer(pattern, text))
        assert len(matches) == 1, key
        match = matches[0]
        literal = f'"{value}"' if match.group(2) == "string" else value
        text = text[:match.start(3)] + literal + text[match.end(3):]
    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    return ("// Q20 trendline buy-limit EA, strategy tester only.\n"
            "// Generated by python/build_trendline_limit_ea.py.\n"
            "// Defaults = saved primary run. RiskReward sets the bar-close target.\n"
            "// MNQcontDTBNT20102026_2, M30; frozen contract/early-close calendars.\n"
            "// Other RiskReward values are unstudied; completed results remain at 1R.\n"
            f"// Original source SHA256: {digest}\n" + text)


def main():
    OUT.write_text(build(), encoding="utf-8")
    print(OUT)


if __name__ == "__main__":
    main()
