"""Prepare the Q17 stand-alone falling-resistance EA and tester jobs (protocol: docs/trendlines/STANDALONE_PROTOCOL.md).

Copies the Q10 baseline research EA (Reports/trend_rr_20261002/RTL_trend_rr.mq5, tag f50_baseline) and adds
mt5/experts/resistance_gate.mqh at the point where the baseline would place its buy stop. A signal that is not a
resistance test is rejected exactly like a MaxRedRun rejection: the old pending order is cancelled, none is placed.
Jobs: `classify` (GateMode=1, no orders: verifies the EA's classification against Q15) and `trade` (GateMode=2).
"""
import json
import re
import shutil

import pandas as pd

from analyze_breach_reclaim import TAG, TREND
from analyze_price_levels import ROOT, sha256
from trend_regimes import ROLLS

RUN = ROOT / "Reports" / "trendlines" / "resistance_standalone_20261004"
EXPERT = "RTL_resistance_gate"
INSTALL = "CodexTrendlineResearch"
GATE = ROOT / "mt5" / "experts" / "resistance_gate.mqh"
PROTOCOL = ROOT / "docs" / "trendlines" / "STANDALONE_PROTOCOL.md"
JOBS = {"classify": 1, "trade": 2}


def rolls_include():
    r = pd.read_csv(ROLLS)
    dates = pd.to_datetime(r.date).dt.strftime("%Y%m%d").tolist()
    assert dates == sorted(dates)
    return ("// Generated by python/prepare_resistance_standalone.py from the roll ledger - do not edit.\n"
            f"// {ROLLS.name}: contract of a bar = instrument of the last roll date <= its session date.\n"
            f"#define CR_COUNT {len(r)}\n"
            f"const int CR_DATE[CR_COUNT] = {{{','.join(dates)}}};\n"
            f"const int CR_ID[CR_COUNT] = {{{','.join(str(x) for x in r.instrument_id)}}};\n")


def main():
    RUN.mkdir(parents=True, exist_ok=True)
    if list(RUN.glob("*.completed.json")):
        raise RuntimeError("Preserve completed runs; do not overwrite their source")
    parent = TREND / "RTL_trend_rr.mq5"
    source = parent.read_text(encoding="utf-8-sig")
    patches = [
        ('#include "trend_rr_research.mqh"',
         '#include "contract_rolls.mqh"\n#include "resistance_gate.mqh"   // Q17 research gate\n#include "trend_rr_research.mqh"'),
        ("   if(!OpenTrendExports()) return INIT_FAILED;",
         "   if(GateMode < 0 || GateMode > 2 || !GateOpenLog()) return INIT_FAILED;\n"
         "   if(!OpenTrendExports()) return INIT_FAILED;"),
        ("\t   Print(\"Red candle (run=\", run,",
         "\t   // Q17 gate: a non-candidate is rejected like any other filter (cancel, no new order).\n"
         "\t   if(!GateAllows())\n\t   {\n\t      CancelOldBuyStops();\n\t      return;\n\t   }\n\n"
         "\t   Print(\"Red candle (run=\", run,"),
        ("   FileClose(f);\n   return(0.0);\n}",
         "   FileClose(f);\n   GateCloseLog();\n"
         "   int gs = FileOpen(g_runTag + \"_gate_stats.csv\", FILE_WRITE|FILE_CSV|FILE_COMMON);\n"
         "   if(gs != INVALID_HANDLE)\n   {\n"
         "      FileWrite(gs, \"gate_mode\", \"gate_errors\", \"resistance_test\", \"poke_through\", \"broken_contact\",\n"
         "                \"not_departed_contact\", \"no_contact\", \"missing_history\", \"contract_roll\", \"invalid_atr\");\n"
         "      FileWrite(gs, GateMode, g_gateErrors, g_gateCounts[0], g_gateCounts[1], g_gateCounts[2], g_gateCounts[3],\n"
         "                g_gateCounts[4], g_gateCounts[5], g_gateCounts[6], g_gateCounts[7]);\n"
         "      FileClose(gs);\n   }\n   return(0.0);\n}"),
    ]
    for before, after in patches:
        assert source.count(before) == 1, before
        source = source.replace(before, after, 1)
    expert = RUN / f"{EXPERT}.mq5"
    expert.write_text(source, encoding="utf-8-sig")
    for name in ("early_closes.mqh", "trend_rr_ledger.mqh", "trend_rr_research.mqh"):
        shutil.copyfile(TREND / name, RUN / name)
    shutil.copyfile(GATE, RUN / GATE.name)
    (RUN / "contract_rolls.mqh").write_text(rolls_include(), encoding="utf-8")
    base_ini = (TREND / f"{TAG}.ini").read_text(encoding="utf-16")
    jobs = []
    for job, mode in JOBS.items():
        tag = f"resistance_standalone_20261004_{job}"
        ini = base_ini
        for key, value in dict(Expert=fr"{INSTALL}\{EXPERT}.ex5", RunTag=tag, Report=f"{tag}.htm").items():
            ini, n = re.subn(rf"(?m)^{key}=.*$", lambda m: f"{key}={value}", ini)
            assert n == 1, key
        ini = ini.replace("[TesterInputs]", f"[TesterInputs]\nGateMode={mode}\nGateN=5\nGateSessions=5\n"
                                            "GateMinSep=10\nGateMinSlope=0.02", 1)
        path = RUN / f"{tag}.ini"
        path.write_text(ini, encoding="utf-16")
        jobs.append(dict(tag=tag, ini=str(path), csv=f"runband_{tag}_1.00.csv", report=f"{tag}.htm",
                         extra_csv=[f"{tag}_signals.csv", f"{tag}_checks.csv", f"{tag}_gate.csv", f"{tag}_gate_stats.csv"]))
    manifest = dict(experiment="Q17 stand-alone falling-resistance candidates, original RTL exit, full-history OHLC",
                    parent_source=str(parent), parent_sha256=sha256(parent), parent_ini=str(TREND / f"{TAG}.ini"),
                    gate_source=str(GATE), gate_sha256=sha256(GATE), expert_sha256=sha256(expert),
                    protocol_sha256=sha256(PROTOCOL) if PROTOCOL.exists() else None, jobs=jobs)
    (RUN / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(expert)


if __name__ == "__main__":
    main()
